version: "3.8"

services: 
    sqlserver:
        container_name: sqlserver
        image: mcr.microsoft.com/mssql/server
        ports: 
            - "1433:1433"
        deploy:
            resources:
                reservations:
                    cpus: "2"
                    memory: 2GB
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=yourStrongPassword12#
        volumes: 
            - sqldata:/var/opt/mssql
    web-app:
        image: yankotaskboardappcr.azurecr.io/taskboard_image_yanko:v1
        container_name: web-app
        build:
            dockerfile: TaskBoard.WebApp/Dockerfile
        ports: 
            - "80:80"
        restart: on-failure

volumes:
    sqldata:
        driver: azure_file
        driver_opts:
            share_name: sql-volume
            storage_account_name: taskboardyankostorage