name: "Terraform Plan/Apply"

on:
  push:
    branches:
      - "main"

env:
  AMR_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AMR_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  AMR_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AMR_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:

  terraform-plan:
    name: "Terraform Plan"
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to the GitHub Action Runner
      - name: Checkout
        uses: actions/checkout@v3
      # Login to Azure via Azure CLI
      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      # Install the latest verssion of the Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      # Initialize a new or existing Terraform working directory
      # Creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        run: az login -u ${{ secrets.AZ_USERNAME }} -p ${{ secrets.AZ_PASSWORD }} && terraform init
      # Generate an execution plan for Terraform
      - name: Terraform Plan
        id: tf-plan
        run: terraform plan -out tfplan
      # Save plan to artifacts
      - name: Publish Terraform Plan
        uses: actions/upload-artifact@v3
        with:
          name: tfplan
          path: tfplan

  terraform-apply:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    needs: [ terraform-plan ]

    steps:
      # Checkout the repository to the github Action Runner
      - name: Checkout
        uses: actions/checkout@v3
      # Install the latest verssion of the Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      # Initialize a new or existing Terraform working directory
      # Creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        run: az login -u ${{ secrets.AZ_USERNAME }} -p ${{ secrets.AZ_PASSWORD }} && terraform init
      # Download saved plan from artifacts
      - name: Download Terraform Plan
        uses: actions/download-artifact@v3
        with:
          name: tfplan
      # Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan